#pragma once

// Request Codes(client → server)
#define LOGIN_REQUEST 1
#define SIGNUP_REQUEST 2

#define LOGOUT_REQUEST 3
#define GET_ROOMS_REQUEST 4
#define GET_PLAYERS_IN_ROOM_REQUEST 5
#define JOIN_ROOM_REQUEST 6
#define CREATE_ROOM_REQUEST 7
#define GET_PERSONAL_STATS_REQUEST 8
#define GET_HIGHSCORE_REQUEST 9

#define CLOSE_ROOM_REQUEST 10
#define START_GAME_REQUEST 11
#define GET_ROOM_STATE_REQUEST 12
#define LEAVE_ROOM_REQUEST 13

#define LEAVE_GAME_REQUEST 14
#define GET_QUESTION_REQUEST 15
#define SUBMIT_ANSWER_REQUEST 16
#define GET_GAME_RESULTS_REQUEST 17

// Response Codes(server → client)
#define LOGIN_RESPONSE 101
#define SIGNUP_RESPONSE 102

#define ERROR_RESPONSE 103
#define LOGOUT_RESPONSE 104
#define GET_ROOMS_RESPONSE 105
#define GET_PLAYERS_IN_ROOM_RESPONSE 106
#define JOIN_ROOM_RESPONSE 107
#define CREATE_ROOM_RESPONSE 108
#define GET_PERSONAL_STATS_RESPONSE 109
#define GET_HIGHSCORE_RESPONSE 110

#define CLOSE_ROOM_RESPONSE 111
#define START_GAME_RESPONSE 112
#define GET_ROOM_STATE_RESPONSE 113
#define LEAVE_ROOM_RESPONSE 114

#define LEAVE_GAME_RESPONSE 115
#define GET_QUESTION_RESPONSE 116
#define SUBMIT_ANSWER_RESPONSE 117
#define GET_GAME_RESULTS_RESPONSE 118


// Status Codes
#define SUCCESS 0