#pragma once

// Request Codes(client → server)
#define LOGIN_REQUEST 1
#define SIGNUP_REQUEST 2
#define LOGOUT_REQUEST 3
#define GET_ROOMS_REQUEST 4
#define GET_PLAYERS_IN_ROOM_REQUEST 5
#define JOIN_ROOM_REQUEST 6
#define CREATE_ROOM_REQUEST 7
#define GET_PERSONAL_STATS_REQUEST 8
#define GET_HIGHSCORE_REQUEST 9

// Response Codes(server → client)
#define LOGIN_RESPONSE 101
#define SIGNUP_RESPONSE 102
#define ERROR_RESPONSE 103
#define LOGOUT_RESPONSE 104
#define GET_ROOMS_RESPONSE 105
#define GET_PLAYERS_IN_ROOM_RESPONSE 106
#define JOIN_ROOM_RESPONSE 107
#define CREATE_ROOM_RESPONSE 108
#define GET_PERSONAL_STATS_RESPONSE 109
#define GET_HIGHSCORE_RESPONSE 110
// Status Codes
#define SUCCESS 0